# Generated by Django 2.2.13 on 2020-08-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('nom1', models.CharField(max_length=30)),
                ('prenom1', models.CharField(max_length=20)),
                ('nom2', models.CharField(blank=True, max_length=30)),
                ('prenom2', models.CharField(blank=True, max_length=20)),
                ('nom3', models.CharField(max_length=30)),
                ('prenom3', models.CharField(max_length=20)),
                ('nom4', models.CharField(blank=True, max_length=30)),
                ('prenom4', models.CharField(blank=True, max_length=20)),
                ('eclairage', models.BooleanField(default=False)),
                ('eclairage_paye', models.BooleanField(default=False)),
                ('entrainement', models.BooleanField(default=False)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Terrain')),
            ],
        ),
    ]
