# Generated by Django 2.2.15 on 2020-09-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='licence_fideration',
            new_name='licence_féderation',
        ),
    ]
