# Generated by Django 2.2.16 on 2020-10-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200930_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_match',
            field=models.CharField(choices=[('E', 'Entrainement'), ('M', 'Match'), ('T', 'Tournoi'), ('D', 'Défi')], default='M', max_length=25),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('juges', models.TextField()),
                ('director', models.CharField(max_length=35)),
                ('trainers', models.TextField()),
                ('players', models.ManyToManyField(related_name='tournaments', to='core.Membre')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='tournoi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='core.Tournament'),
            preserve_default=False,
        ),
    ]
