# Generated by Django 2.2.13 on 2020-08-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35, unique=True)),
                ('tel', models.CharField(blank=True, max_length=13, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
