# Generated by Django 2.2.16 on 2020-10-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201016_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tournoi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='core.Tournament'),
        ),
    ]
