# Generated by Django 2.2.13 on 2020-08-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='nom1',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nom2',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nom3',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nom4',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='prenom1',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='prenom2',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='prenom3',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='prenom4',
        ),
        migrations.AddField(
            model_name='reservation',
            name='membre1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_1', to='core.Membre'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='membre2',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_2', to='core.Membre'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='membre3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_3', to='core.Membre'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='membre4',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_4', to='core.Membre'),
        ),
    ]
