# Generated by Django 2.2.16 on 2020-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201016_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='director',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='juges',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='trainers',
            field=models.TextField(blank=True),
        ),
    ]
