# Generated by Django 2.2.13 on 2020-08-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200826_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='membre1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_1', to='core.Membre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='membre2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_2', to='core.Membre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='membre3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_3', to='core.Membre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='membre4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_4', to='core.Membre'),
        ),
    ]
