# Generated by Django 2.2.16 on 2020-10-20 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201020_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 9, 49, 3, 559529, tzinfo=utc)),
        ),
    ]
