# Generated by Django 2.2.15 on 2020-09-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200908_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ('nom',)},
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexe',
            field=models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], default='H', max_length=2),
        ),
    ]
