# Generated by Django 2.2.16 on 2020-10-21 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201020_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type_tournoi',
            field=models.CharField(default='TCMT', max_length=25),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 9, 15, 23, 536181, tzinfo=utc)),
        ),
    ]
