# Generated by Django 2.2.15 on 2020-09-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200910_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='tournoi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.Terrain'),
        ),
    ]
