# Generated by Django 2.2.15 on 2020-09-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200914_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='core.Membre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='membre1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_1', to='core.Membre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='membre3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_3', to='core.Membre'),
        ),
    ]
