# Generated by Django 2.2.16 on 2020-10-24 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('core', '0010_auto_20201024_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 10, 23, 21, 910788, tzinfo=utc)),
        ),
    ]
