# Generated by Django 2.2.16 on 2020-10-24 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201024_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 11, 17, 59, 91178, tzinfo=utc)),
        ),
    ]
