# Generated by Django 2.2.15 on 2020-09-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200915_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotisation',
            name='reste_paye',
        ),
        migrations.AddField(
            model_name='cotisation',
            name='montant',
            field=models.PositiveSmallIntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
