# Generated by Django 2.2.15 on 2020-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200918_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='categorie',
            field=models.ManyToManyField(blank=True, related_name='membres', to='core.Categorie'),
        ),
    ]
