# Generated by Django 2.2.15 on 2020-09-23 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20200922_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='membre1',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='membre2',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='membre3',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='membre4',
        ),
        migrations.AddField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
