# Generated by Django 2.2.15 on 2020-09-25 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_reservation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
