# Generated by Django 2.2.15 on 2020-09-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cotisation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='profession',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
