# Generated by Django 2.2.15 on 2020-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_membre_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type_match',
            field=models.CharField(choices=[('E', 'Entrainement'), ('M', 'Match'), ('T', 'Tournoi')], default='Match', max_length=25),
        ),
    ]
