# Generated by Django 2.2.15 on 2020-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_reservation_type_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type_match',
            field=models.CharField(choices=[('E', 'Entrainement'), ('M', 'Match'), ('T', 'Tournoi')], default='M', max_length=25),
        ),
    ]
