# Generated by Django 2.2.16 on 2020-10-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.CharField(blank=True, max_length=35)),
                ('trainers', models.TextField(blank=True)),
            ],
        ),
    ]
